import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Following Linkedin Learning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Navbar content should go here, and should somehow persist through all pages, except when viewing recipes</p>
          <p>Navbar should always move to bottom when in mobile</p>
          <p>should figure out how to import hamburger menu too</p>
        </div>

        <div className={styles.center}>
          <h1>THIS IS YOUR HOMEPAGE</h1>
          <p>Users who are not logged in are taken here</p>
        </div>

        <div className={styles.grid}>
          {/* Code from ref example. Keep only unitl new content replaces it */}
          <Link
            href="/learn/next"
          >
              <h2>
                Learn Next <span>-&gt;</span>
              </h2>
          </Link>
        </div>
      </main>
    </>
  );
}
